### PR TITLE
Allows [lazyLoad] to have condition coding

### PR DESCRIPTION
**Pull request by natqiu**
I want to set [lazyLoad]="Condition? url : null", but if  Condition == false then the div will transform into:
`<div class="ng2-lazyloaded" style="background-image: url("undefined");"></div>`.

### CODE REVIEW

**Comment by tjoskar** [comment]
HI,

Thanks for your PR. Is there any use case where you can't use `*ngIf`? Like:

```html
<div [lazyLoad]="url" *ngIf="condition"></div>
```

**Comment by tjoskar** [comment]
In your use case, can the condition be false and then, at any time, switch to true or is the condition always true/false?

It may be a better approach to remove the event listener if the url is _falsy_. Something like:

```diff
     }
 
     setImage(image) {
+        if (!image) {
+            return;
+        }
         const element = this.elementRef.nativeElement;
         const isImgNode = this.elementRef.nativeElement.nodeName.toLowerCase() === 'img';
         if (isImgNode) {
```

Otherwise will `isVisible` be unnecessary called for every scroll event.

**Comment by natqiu** [comment]
Thank you for your response

The first approach is not what I want.
I want to keep the div container and using Condition to display image

The second approach .
Originally, I would like to change in the setImage() method.
If the judge in the setImage() method, the element was still added the className: ng2-lazyloaded

Provide another approach? Something like:
```ts
ngAfterContentInit() {
         this.scrollSubscription = getScrollListener(this._scrollTarget)
             .filter(() => !!this.lazyImage) // remove the event listener if the lazyImage is falsy.**
             .filter(() => this.isVisible())
             .take(1)
             .switchMap(() => [this.loadImage(this.lazyImage))]
```


Can you teach me how to add diff code in comment area? Like in your comment, the diff code had light green background color.

**Comment by tjoskar** [comment]
I'm buying what you're saying and I will accept the PR.

Regarding showing a diff. I often make some changes in my editor and copy the result from `git diff` which looks something like:

```
      ngAfterContentInit() {
         this.scrollSubscription = getScrollListener(this._scrollTarget)
+            .filter(() => !!this.lazyImage)
             .filter(() => this.isVisible())
             .take(1)
             .switchMap(() => this.loadImage(this.lazyImage))
```  

and then set the code type to `diff` (the same way you setting the type to javascript above).

```diff
      ngAfterContentInit() {
         this.scrollSubscription = getScrollListener(this._scrollTarget)
+            .filter(() => !!this.lazyImage)
             .filter(() => this.isVisible())
             .take(1)
             .switchMap(() => this.loadImage(this.lazyImage))
```

**Comment by tjoskar** [comment]
I saw that you added a new [commit](https://github.com/natqiu/ng2-lazyload-image/commit/4f3398b32e2a5d4d210a4fc6c2196f5faba725f4) in your master branch but you are making a PR from your patch-1 branch. Are you planing to create a new PR?

**Comment by natqiu** [comment]
You can ignore. The commit I want to try diff code format, which is operational mistakes

**Comment by tjoskar** [comment]
@natqiu I will close this PR now. Let me know if you are still interested in this feature.

**Pull request closed without merging**
